import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "keen-slider/keen-slider.min.css";
import { useKeenSlider } from "keen-slider/react";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const images = ["/burger.jpg", "/pizza.jpg"];

export default function Home() {
  const [opacities, setOpacities] = React.useState([]);

  const [sliderRef] = useKeenSlider({
    slides: images.length,
    loop: true,
    detailsChanged(s) {
      const new_opacities = s.track.details.slides.map(
        (slide) => slide.portion
      );
      setOpacities(new_opacities);
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.sideBar}>
          <Image src="/logo.png" alt="Big Eats" width={200} height={200} />
          <h1 className={styles.name}>Big Eats</h1>
          <div className={styles.buttonBox}>
            <button className={styles.button}>Home</button>
            <button className={styles.button}>Menu</button>
            <button className={styles.button}>About Us</button>
          </div>
        </div>
        <div className={styles.content}>
          <h1 className={styles.title}>Welcome to Big Eats</h1>
          <h3 className={styles.description}>Big Appetite. No Problem.</h3>
          <div className={styles.homeContent}>
            <div ref={sliderRef} className="fader">
              {images.map((src, idx) => (
                <div
                  key={idx}
                  className="fader__slide"
                  style={{ opacity: opacities[idx] }}
                >
                  <img style={{ width: "500px", height: "400px" }} src={src} />
                </div>
              ))}
            </div>
            <div className={styles.descBox}>
              Welcome to Big Eats, the home of larger-than-life dining
              experiences in Townville. <br></br>
              <br></br>Discover our menu of mouthwatering dishes that are
              guaranteed to satisfy your appetite. From towering burgers to
              gigantic desserts, we serve up colossal portions that will leave
              you in awe.
              <br></br>
              <br></br> Come and experience the sensation of Big Eats, the
              ultimate destination for food enthusiasts seeking a taste
              adventure like no other.
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
